services:
  hugo-blog:
    build: ./hugo
    command: server --source /app/site --destination /app/public --baseURL http://localhost:1313 --appendPort=false
    volumes:
      - ./site:/app/site
      - ./public:/app/public
    ports:
      - "1313:1313"