baseURL = 'http://chluebi.com/'
languageCode = 'en-us'
title = 'Conundrum'
theme = 'hugo-theme-m10c'

paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "chluebi"
  description = "Computer Science Student who is interested in Mathematics, Formal Systems, Philosophy, AI, Structural Analysis, Media Analysis, the Videogames Industry, Boardgames, Combinatorial Game Theory, In-Silico Ecosystems, Linguistics, Jerma, Competitive Programming, Volleyball, Democracy, Game Design and sometimes even Computer Science."
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/chluebi"


[params.style]
    darkestColor = "#242930"
    darkColor = "#353b43"
    lightColor = "#afbac4"
    lightestColor = "#ffffff"
    primaryColor = "#8959d1"