baseURL = 'http://chluebi.com/'
languageCode = 'en-us'
title = 'Conundrum'
theme = 'hugo-theme-m10c'

enableRobotsTXT = true

paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "chluebi"
  description = "Blog of a Computer Science Student and Person"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/chluebi"


[params.style]
    darkestColor = "#242930"
    darkColor = "#353b43"
    lightColor = "#828a91"
    lightestColor = "#ffffff"
    primaryColor = "#8959d1"