baseURL = "https://chluebi.github.io/website/"
canonifyURLs = true
languageCode = 'en-us'
title = 'Conundrum'
theme = 'hugo-theme-m10c'

enableRobotsTXT = true

pagination.pagerSize = 8

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

[params]
  author = "chluebi"
  description = "Blog of a Computer Science Student and Person"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/chluebi"


[params.style]
    darkestColor = "#131516"
    darkColor = "#242930"
    lightColor = "#bec9d3"
    lightestColor = "#ffffff"
    primaryColor = "#b79ae2"
